[build]
publish = "dist"
command = "pnpm --filter stream-markdown build && pnpm run build"

[build.environment]
NPM_FLAGS = "--version"
NODE_VERSION = "22"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
